# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de5d66db326354bce236b6c939927d713c5c2367b88a266e9ef929528f7a09b694ef92908509757e2513213fa854a6a0d6638bbef6f783a4a8e2b3045d0a65cb

test:
  secret_key_base: f6ff88c490e9f9441fa60eb82a72a60c18ff968c4c9b1c183b84077f8dab2f146170c5b80b1a4e74178cb0cfa5bfc43a3a697fb4f1a0418a34ec30722cc3b7aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
